"""Group keyboards package."""

from .cmds import GroupsCmdsMenu, groups_cmds_kb
from .main import (
    GroupAccessApplyMenu,
    GroupAccessMenu,
    GroupManagementMenu,
    GroupMemberActionMenu,
    GroupMemberDetailMenu,
    GroupMembersMenu,
    GroupServiceMessagesApplyMenu,
    GroupServiceMessagesMenu,
    GroupSettingsMenu,
    GroupsMenu,
    group_access_kb,
    group_management_kb,
    group_member_detail_kb,
    group_members_kb,
    group_service_messages_kb,
    group_settings_kb,
    groups_kb,
    short_name,
)

__all__ = [
    "GroupsMenu",
    "GroupsCmdsMenu",
    "GroupManagementMenu",
    "GroupSettingsMenu",
    "GroupAccessMenu",
    "GroupAccessApplyMenu",
    "GroupMembersMenu",
    "GroupMemberDetailMenu",
    "GroupMemberActionMenu",
    "GroupServiceMessagesMenu",
    "GroupServiceMessagesApplyMenu",
    "groups_kb",
    "groups_cmds_kb",
    "group_management_kb",
    "group_settings_kb",
    "group_access_kb",
    "group_members_kb",
    "group_member_detail_kb",
    "group_service_messages_kb",
    "short_name",
]
