name: Docker CI/CD

on:
  push:
    branches:
      - main
      - dev
      - feature/**
    tags:
      - 'v*.*.*'  # Build semver tags like v1.2.3

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: stp-team/stpsher

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tag by Git SHA
            type=sha,format=short
            # Tag by branch name (e.g., main, dev)
            type=ref,event=branch
            # Tag by semver if pushed with a version tag
            type=semver,pattern={{version}}
            # Always push "latest" from main branch
            type=raw,value=latest,enable={{ eq(github.ref_name, 'main') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
